# Generated by Django 6.0.3 on 2026-04-11 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="licenciatura",
            name="ects",
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name="licenciatura",
            name="grau",
            field=models.CharField(default="Licenciatura", max_length=50),
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ano", models.IntegerField()),
                ("semestre", models.IntegerField()),
                ("ects", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="ucs/")),
                ("link_docente_lusofona", models.URLField(blank=True)),
                (
                    "licenciaturas",
                    models.ManyToManyField(
                        related_name="unidades_curriculares",
                        to="portfolio.licenciatura",
                    ),
                ),
            ],
        ),
    ]
