# Generated by Django 6.0.3 on 2026-04-11 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_makingof_tfc_competencia_formacao"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="e_favorito",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="link_relatorio",
            field=models.URLField(blank=True, null=True),
        ),
    ]
