# Generated by Django 6.0.3 on 2026-04-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tfc_e_favorito_alter_tfc_link_relatorio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tfc",
            name="e_favorito",
        ),
        migrations.AddField(
            model_name="tfc",
            name="curso",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="autor",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="link_relatorio",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="orientador",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
