# Generated by Django 6.0.3 on 2026-04-11 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_remove_tfc_e_favorito_tfc_curso_alter_tfc_autor_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projeto",
            old_name="github_url",
            new_name="repositorio",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="conceitos_aplicados",
        ),
        migrations.RemoveField(
            model_name="projeto",
            name="video_link",
        ),
        migrations.AddField(
            model_name="projeto",
            name="ano",
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(to="portfolio.tecnologia"),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="uc",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.unidadecurricular",
            ),
        ),
    ]
