# Generated by Django 6.0.3 on 2026-04-22 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_rename_github_url_projeto_repositorio_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TipoTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
