# Generated by Django 6.0.3 on 2026-04-22 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_tipotecnologia_tecnologia_descricao"),
    ]

    operations = [
        migrations.AddField(
            model_name="tecnologia",
            name="tipo",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="portfolio.tipotecnologia",
            ),
            preserve_default=False,
        ),
    ]
